# Generated by Django 3.2.3 on 2021-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog.jpg', null=True, upload_to='images'),
        ),
    ]
