# Generated by Django 3.2.3 on 2021-05-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
