# Generated by Django 3.2.3 on 2021-05-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
