# Generated by Django 3.2.3 on 2021-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
    ]
