# Generated by Django 3.2.3 on 2021-05-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_comment_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogComment',
        ),
    ]
