# Generated by Django 3.2.3 on 2021-05-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcomment'),
        ),
    ]
