# Generated by Django 3.2.3 on 2021-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. Bhuvneshwer', 'Dr. Bhuvneshwer'), ('Dr. Ishwari', 'Dr. Ishwari'), ('Dr. Shriwastav', 'Dr. Shriwastav')], default='', max_length=255),
        ),
    ]
