# Generated by Django 3.2.3 on 2021-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_orders_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
