# Generated by Django 3.2.3 on 2021-06-06 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_auto_20210606_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=14)),
                ('experience', models.CharField(max_length=14)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
