# Generated by Django 3.2.3 on 2021-06-06 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_auto_20210606_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='CV',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='upload_file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
