# Generated by Django 3.2.3 on 2021-06-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_alter_recruitment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='timeStamp',
        ),
    ]
