# Generated by Django 3.2.3 on 2021-06-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
