# Generated by Django 3.2.3 on 2021-05-29 16:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
