# Generated by Django 3.2.3 on 2021-05-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_edu_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edu',
        ),
    ]
